services:
  - type: web
    name: mybc
    plan: free
    env: go
    repo: https://github.com/iseauu/bc.git
    branch: master
    buildCommand: go build -ldflags="-s -w" -tags netgo -trimpath -o mybc main.go
    startCommand: ./mybc